apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: fleetman-microservices
spec:
  volumeName: fleetman-mongodb
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fleetman-mongodb
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/mnt/fleetman-mongodb"
    type: DirectoryOrCreate
  claimRef:
    namespace: fleetman-microservices
    name: mongo-pvc

