apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  values:
    replicas: 1

    secret:
      enabled: true
      password: "password" # move to external secret

    volumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 30Gi

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: mkcert-issuer
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

      className: "nginx"
      pathtype: ImplementationSpecific
      hosts:
        - host: elasticsearch.kindcluster.dev
          paths:
            - path: /
      tls:
        - secretName: elasticsearch-tls
          hosts:
            - elasticsearch.kindcluster.dev
