---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trellis-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: trellis
    - name: secret-stores
  interval: 10m0s
  retryInterval: 30s
  timeout: 15m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/dev-cluster/components/apps/trellis-secrets
  prune: true
  wait: true
