apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
  - deployment.yaml

secretGenerator:
  - name: redis-tls
    namespace: redis-insight
    type: kubernetes.io/tls
    files:
      - tls.crt=redis.kindcluster.dev.pem
      - tls.key=redis.kindcluster.dev-key.pem

generatorOptions:
  disableNameSuffixHash: true
