---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../../apps/kuard/flux-system
- ../../../../../apps/redis/flux-system
- ../../../../../apps/redis-insight/flux-system

patches:
- path: patches/kuard.yaml
- path: patches/redis.yaml
- path: patches/redis-insight.yaml