---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-postgres-data
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /mnt/data-pool-1/keycloak-postgres-data
  claimRef:
    namespace: keycloak
    name: keycloak-postgres-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgres-data
  namespace: keycloak
spec:
  volumeMode: Filesystem
  volumeName: keycloak-postgres-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
