apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-operator-system
resources:
  - namespace.yaml
  - postgres-operator-helm-release.yaml
  - postgres-operator-ui-helm-release.yaml
