apiVersion: v1
kind: Service
metadata:
  name: kuard
  namespace: kuard
  labels:
    app: kuard
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard
    tier: frontend
    environment: dev
