apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-data
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/data-pool-1/vault-data
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: gitops-flux.local/data-pool-1
          operator: In
          values:
          - 'true'
  claimRef:
    namespace: vault
    name: data-vault-0
