apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  values:
    controller:
      hostPort:
        enabled: false
      service:
        type: LoadBalancer
        annotations:
          metallb.io/loadBalancerIPs: "172.88.0.200"
