apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  namespace: kuard
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    spec:
      containers:
        - name: kuard
          image: gcr.io/kuar-demo/kuard-amd64:1
          env:
            # just to show if env array can be patched
            - name: CONTAINER_MEMORY_LIMIT_KIBIBYTES
              valueFrom:
                resourceFieldRef:
                  divisor: 1Mi
                  resource: limits.memory
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
