apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../../components/kuard

labels:
- includeSelectors: true
  pairs:
    environment: dev

patches:
- path: deployment.yaml
