---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-issuer.yaml
- cert-manager.yaml
- elasticsearch.yaml
- filebeat.yaml
- ingress-nginx.yaml
- kibana.yaml
- logstash.yaml
- redis.yaml
- redis-insight.yaml
- monitoring.yaml
- tofu-controller.yaml
- weave-gitops.yaml
