---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-issuer.yaml
- cert-manager.yaml
- elasticsearch.yaml
- filebeat.yaml
- ingress-nginx.yaml
- kibana.yaml
- kube-prometheus-stack.yaml
- kubeclaw-instances.yaml
- logstash.yaml
- metallb.yaml
- metallb-config.yaml
- mongodb.yaml
- monitoring.yaml
- openclaw-operator-system.yaml
- openclaw-operator-instances.yaml
- rabbitmq.yaml
- redis.yaml
- redis-insight.yaml
- tofu-controller.yaml
- weave-gitops.yaml
