---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/dev-cluster/components/infrastructure/flux-system/weave-gitops
  prune: true
  wait: true
