apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-example
  namespace: secret-lab-eso
spec:
  refreshPolicy: Periodic
  refreshInterval: 30s
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: eso-example
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: message
    remoteRef:
      key: eso/example
      property: message
