apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  interval: 1h
  releaseName: sealed-secrets-controller
  chart:
    spec:
      chart: sealed-secrets
      version: "2.6.9"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  values:
    secretName: "sealed-secrets-key"
    keyrenewperiod: "1h30m"
