apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  interval: 1h
  releaseName: rabbitmq
  chart:
    spec:
      chart: rabbitmq
      version: "15.5.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
