apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: mongodb
spec:
  values:
    ## @param architecture MongoDB(&reg;) architecture (`standalone` or `replicaset`)
    ##
    architecture: replicaset
    ## MongoDB(&reg;) Authentication parameters
    ##
    auth:
      ## @param auth.enabled Enable authentication
      ## ref: https://docs.mongodb.com/manual/tutorial/enable-authentication/
      ##
      enabled: true
      ## @param auth.rootUser MongoDB(&reg;) root user
      ##
      rootUser: root
      ## @param auth.rootPassword MongoDB(&reg;) root password
      ## ref: https://github.com/bitnami/containers/tree/main/bitnami/mongodb#setting-the-root-user-and-password-on-first-run
      ##
      rootPassword: "password"
      ## MongoDB(&reg;) custom users and databases
      ## ref: https://github.com/bitnami/containers/tree/main/bitnami/mongodb#creating-a-user-and-database-on-first-run
      ## @param auth.usernames List of custom users to be created during the initialization
      ## @param auth.passwords List of passwords for the custom users set at `auth.usernames`
      ## @param auth.databases List of custom databases to be created during the initialization
      ##
      usernames: []
      passwords: []
      databases: []
      ## @param auth.username DEPRECATED: use `auth.usernames` instead
      ## @param auth.password DEPRECATED: use `auth.passwords` instead
      ## @param auth.database DEPRECATED: use `auth.databases` instead
      ##
      username: ""
      password: ""
      database: ""
      ## @param auth.replicaSetKey Key used for authentication in the replicaset (only when `architecture=replicaset`)
      ##
      replicaSetKey: ""
      ## @param auth.existingSecret Existing secret with MongoDB(&reg;) credentials (keys: `mongodb-passwords`, `mongodb-root-password`, `mongodb-metrics-password`, `mongodb-replica-set-key`)
      ## NOTE: When it's set the previous parameters are ignored.
      ##
      existingSecret: ""
    tls:
      ## @param tls.enabled Enable MongoDB(&reg;) TLS support between nodes in the cluster as well as between mongo clients and nodes
      ##
      enabled: false
      mTLS:
        ## @param tls.mTLS.enabled IF TLS support is enabled, require clients to provide certificates
        enabled: true
      ## @param tls.autoGenerated Generate a custom CA and self-signed certificates
      ##
      autoGenerated: true
      ## @param tls.existingSecret Existing secret with TLS certificates (keys: `mongodb-ca-cert`, `mongodb-ca-key`)
      ## NOTE: When it's set it will disable secret creation.
      ##
      existingSecret: ""
      ## Add Custom CA certificate
      ## @param tls.caCert Custom CA certificated (base64 encoded)
      ## @param tls.caKey CA certificate private key (base64 encoded)
      ##
      caCert: ""
      caKey: ""
      ## @param tls.pemChainIncluded Flag to denote that the Certificate Authority (CA) certificates are bundled with the endpoint cert.
      ## Certificates must be in proper order, where the top certificate is the leaf and the bottom certificate is the top-most intermediate CA.
      ##
      pemChainIncluded: false
      standalone:
        ## @param tls.standalone.existingSecret Existing secret with TLS certificates (`tls.key`, `tls.crt`, `ca.crt`) or (`tls.key`, `tls.crt`) with tls.pemChainIncluded set as enabled.
        ## NOTE: When it's set it will disable certificate self-generation from existing CA.
        ##
        existingSecret: ""
      replicaset:
        ## @param tls.replicaset.existingSecrets Array of existing secrets with TLS certificates (`tls.key`, `tls.crt`, `ca.crt`) or (`tls.key`, `tls.crt`) with tls.pemChainIncluded set as enabled.
        ## existingSecrets:
        ##  - "mySecret-0"
        ##  - "mySecret-1"
        ## NOTE: When it's set it will disable certificate self-generation from existing CA.
        ##
        existingSecrets: []
      hidden:
        ## @param tls.hidden.existingSecrets Array of existing secrets with TLS certificates (`tls.key`, `tls.crt`, `ca.crt`) or (`tls.key`, `tls.crt`) with tls.pemChainIncluded set as enabled.
        ## existingSecrets:
        ##  - "mySecret-0"
        ##  - "mySecret-1"
        ## NOTE: When it's set it will disable certificate self-generation from existing CA.
        ##
        existingSecrets: []
      arbiter:
        ## @param tls.arbiter.existingSecret Existing secret with TLS certificates (`tls.key`, `tls.crt`, `ca.crt`) or (`tls.key`, `tls.crt`) with tls.pemChainIncluded set as enabled.
        ## NOTE: When it's set it will disable certificate self-generation from existing CA.
        ##
        existingSecret: ""
    ## @param replicaSetName Name of the replica set (only when `architecture=replicaset`)
    ## Ignored when mongodb.architecture=standalone
    ##
    replicaSetName: rs0
    ## @param replicaSetHostnames Enable DNS hostnames in the replicaset config (only when `architecture=replicaset`)
    ## Ignored when mongodb.architecture=standalone
    ## Ignored when externalAccess.enabled=true
    ##
    systemLogVerbosity: 2
