---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sealed-example
  namespace: secret-lab-sealed
spec:
  encryptedData:
    message: AgBEzWT9mkQbhs27O+NDUg7WZep57wlTymsSBMhFBfgZKaDcJJTxqLj8aqz/QcNijnsyK6GyIspRSUVRwbzPdoiugoKyf9qQ8tEXHTGCETgUz7oW8gHy/8lSb9D52vcKR5G9lLZmed3voKNRA1K4T4Ki5c5rH3yr9HrFn19i9WQYa/Az2HQsW/1njWYo4Ooi+sCQW4Pjl8P4TW+i/z71V2O3JBIbTMM8J3BxLYinXedaYUCbFbX7IPWah5HlgPwYDIAdpyYNpU38dx7ceC4ZLn7sFllPW52ylxu0FkCbdlyp3dlHZB518Thbz2/IeYL5xgV9dsbZUkcbCewKHqvLTXmh6cEU8vVn5F1i1gmPakgJhzoP7kFU+NKQ5HtmEqlkeBExP29GQMNMMSixpu5qIPq+jyUWy57/lEXf0v4C9K4yzGQLoJjm6nKeyg9gu2H+yCbRZMwf2Qwdwh6XFxNNfwET1d97SpHiJuyzAVIHxSZu3RYcAtRUi2d16ppOUf1CeN0Sl1mFU4UF4ikElUlV/5CoW/hgyyqhDLyhQ6KOwnOtM5Kg0cYyy/PecU3LZTZ0mmglBf+ENluIIND+aVnRVtxsXpEmEh3QcCGX2ASSZICps0jHQDM68Q1T0Vi4SJXzNK2kJJZzPP8kgB9kLbOFIUd0VeQVhC6LNZwcU6lfe4uYb7F1zRMio+3uKjl2aCTIQLADFd1mfU9ONH00rZ/mnBM=
  template:
    metadata:
      name: sealed-example
      namespace: secret-lab-sealed
