---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sealed-example
  namespace: secret-lab-sealed
spec:
  encryptedData:
    message: AgAFRkgsqgkHUhhWzhLadM9+r1cIlpV8xr6Km4hDm6/dgDv/pr8IBsHy02qljceKdIqNA5yYkZOnwzdc4YG90TzWEuo3BolbE3KJjPpxGGjET2VfxyfExpyA3jAkLDx4e7llVs3upcZv+ISVD70lx1GPtWaU2Pob4YOGavNCSIGzgMLxMDhmEpRs9Eh6bSiE34u7MlntdC+71bigPJRxeH7yXH80uxOD9zErAJzCPC6xKTfOhQQ9oy4XRIcouGu+IQFpUhiH0aQU46aDLl4MzplKFklz2eqMCzEMJUiaiO2XluMeS7qRT7ZmN8G5+kZxf09mg7yrh4wOVtg3ZHKSob9412wIbL5V+TPhtlKehMeQt8p5/Dg2n7MF8RZAJG0Az1bOz75FOC7ZkWFa5NgjxyK71253NxICjGtEipCNRoG4Awjvi9zYhhiOHzIR+hsW9imBB/qB3iE1+fHj1u+CrA9Cr72Xy03SOaIMmY+/DRDUwvA7ut+OcFIYoOq9c0HckatW2iBVyxHsma9aBalaB4nJ/2ti2dM2iEcbt1Q1iM2l0qkDn1D0SHlaGo3bDVLR8Br/aP6cFtoKWFQt4sYuVtqdWl46h04RocKNp3HLl2pvZTsllXJFkDjQMA5qJKJtHNlUM3Ohc8C8mdxmriI4yCphZYfJ4/m0nTA3i/jrB2GFl+Gdx77vnXpVUZq2YjLiMU/nb2ARQ/7tRZ3+/UHE5MA=
  template:
    metadata:
      name: sealed-example
      namespace: secret-lab-sealed
