apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  namespace: observability
spec:
  values:
    resources:
      limits:
        cpu: 500m
        memory: 768Mi
      requests:
        cpu: 100m
        memory: 256Mi
    service:
      enabled: true
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: mkcert-issuer
      hosts:
        - host: otlp.kindcluster.dev
          paths:
            - path: /
              pathType: Prefix
              port: 4318
      tls:
        - secretName: otlp-tls
          hosts:
            - otlp.kindcluster.dev
