apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../components/observability/opentelemetry-collector
  - ingress-grpc.yaml

patches:
  - path: helm-release.yaml
