apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../../apps/kuard

labels:
- includeSelectors: true
  pairs:
    environment: production

patches:
- path: deployment.yaml
