---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: logstash
  namespace: flux-system
spec:
  dependsOn:
    - name: elasticsearch
  interval: 10m0s
  retryInterval: 30s
  timeout: 30m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: SET-IT
  prune: true
  wait: true
