---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../../infrastructure/cert-manager/flux-system
- ../../../../../infrastructure/elasticsearch/flux-system
- ../../../../../infrastructure/ingress-nginx/flux-system
- ../../../../../infrastructure/logstash/flux-system

- cert-issuer/kustomize-toolkit.yaml

patches:
- path: patches/cert-manager.yaml
- path: patches/elasticsearch.yaml
- path: patches/ingress-nginx.yaml
- path: patches/logstash.yaml
