---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

- ../../../../../infrastructure/cert-manager/flux-system
- ../../../../../infrastructure/ingress-nginx/flux-system
- ../../../../../infrastructure/monitoring/namespace.yaml
- ../../../../../infrastructure/monitoring/elasticsearch/flux-system
- ../../../../../infrastructure/monitoring/filebeat/flux-system
- ../../../../../infrastructure/monitoring/kibana/flux-system
- ../../../../../infrastructure/monitoring/logstash/flux-system
- cert-issuer/kustomize-toolkit.yaml

patches:
- path: patches/cert-manager.yaml
- path: patches/elasticsearch.yaml
- path: patches/filebeat.yaml
- path: patches/kibana.yaml
- path: patches/ingress-nginx.yaml
- path: patches/logstash.yaml
