apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: watchtower
  namespace: watchtower
spec:
  values:
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
