kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: local-dind-cluster
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/16"
nodes:
  - role: control-plane
    image: kindest/node:v1.35.1@sha256:05d7bcdefbda08b4e038f644c4df690cdac3fba8b06f8289f30e10026720a1ab
  - role: worker
    image: kindest/node:v1.35.1@sha256:05d7bcdefbda08b4e038f644c4df690cdac3fba8b06f8289f30e10026720a1ab
    extraMounts:
      - hostPath: ${SCRIPT_DIR}/worker-1-localpathprovisioner-data
        containerPath: /mnt/data       # Where it appears inside the kind node
  - role: worker
    image: kindest/node:v1.35.1@sha256:05d7bcdefbda08b4e038f644c4df690cdac3fba8b06f8289f30e10026720a1ab
    extraMounts:
      - hostPath: ${SCRIPT_DIR}/worker-2-localpathprovisioner-data
        containerPath: /mnt/data       # Where it appears inside the kind node
