apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - api-gateway-deployment.yml
  - api-gateway-svc.yml
  - mongo-deployment.yml
  - mongo-svc.yml
  - position-simulator-deployment.yml
  - position-tracker-deployment.yml
  - position-tracker-svc.yml
  - queue-deployment.yml
  - queue-svc.yml
  - webapp-deployment.yml
  - webapp-svc.yml
