apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../../components/headlamp
- service-account.yaml
- cluster-role-binding.yaml

patches:
  - path: helm-release.yaml
