apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-example
  namespace: secret-lab-vso
spec:
  vaultAuthRef: vault
  type: kv-v2
  mount: secret-lab
  path: vso/example
  refreshAfter: 30s
  hmacSecretData: true
  destination:
    create: true
    overwrite: false
    name: vso-example
  rolloutRestartTargets:
  - kind: Deployment
    name: consumer
