apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  interval: 1h
  releaseName: redis
  chart:
    spec:
      chart: redis-cluster
      version: "11.4.6"
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
values:

